package productCodes

// GetMasterCardProductName Returns the product name for the given product code.
func GetMasterCardProductName(productCode *string) string {
	var v, ex = masterCardProductTypes[*productCode]
	if ex {
		return v
	}
	return ""
}

var masterCardProductTypes = map[string]string{
	"AMX": "American Express",
	"BPC": "Bill Pay Commercial",
	"BPD": "Business Premium Debit",
	"CBL": "Carte Blanche",
	"CIR": "Cirrus",
	"DAG": "Gold Debit Mastercard® Salary",
	"DAP": "Platinum Debit Mastercard® Salary",
	"DAS": "Standard Debit Mastercard® Salary",
	"DCC": "Diners Club",
	"DLG": "Debit Mastercard Gold—Delayed Debit",
	"DLH": "Debit Mastercard World Embossed—Delayed Debit",
	"DLI": "Debit Mastercard Standard ISIC Student Card—Delayed Debit",
	"DLP": "Debit Mastercard Platinum—Delayed Debit",
	"DLS": "Debit Mastercard Card—Delayed Debit",
	"DLU": "Debit Mastercard Unembossed—Delayed Debit",
	"DOS": "Standard Debit Mastercard® Social",
	"DSV": "Discover",
	"DWF": "Debit Mastercard Humanitarian Prepaid",
	"EXC": "ADP/Exchange",
	"GCP": "Mastercard Shop & Split Premium",
	"GCS": "Mastercard Shop & Split Standard",
	"HNR": "Honor3",
	"ITT": "Instant Teller",
	"JCB": "Japanese Credit Bureau",
	"LNC": "LINC New York",
	"MAB": "World Elite Mastercard® for Business",
	"MAC": "Mastercard Corporate World Elite®",
	"MAP": "Mastercard Commercial Payments Account",
	"MAQ": "Mastercard Prepaid Commercial Payments Account",
	"MBA": "Mastercard B2B Product 2a",
	"MBB": "Mastercard Prepaid Consumer",
	"MBC": "Mastercard Prepaid Voucher",
	"MBD": "Mastercard Professional Debit Business Card",
	"MBE": "Mastercard® Electronic Business Card",
	"MBF": "Mastercard Alimentação (Food) (MBF–Prepaid Mastercard Food)",
	"MBG": "Mastercard B2B Product 3a",
	"MBH": "Mastercard B2B Product 4a",
	"MBI": "Mastercard B2B Product 5a",
	"MBJ": "Mastercard B2B Product 6a",
	"MBM": "Mastercard® Refeição (Meal) (MBM–Prepaid Mastercard Meal)",
	"MBP": "Mastercard Corporate Prepaid",
	"MBS": "Mastercard B2B Product 1",
	"MBT": "Mastercard Corporate Prepaid Travel",
	"MBW": "World Mastercard® Black Edition—Debit",
	"MCA": "Mastercard Electronic Basic Card",
	"MCB": "Mastercard BusinessCard® Card Mastercard Corporate Card®",
	"MCC": "Mastercard Card",
	"MCE": "Mastercard Electronic™ Card",
	"MCF": "Mastercard Corporate Fleet Card®",
	"MCG": "Gold Mastercard® Card",
	"MCH": "Mastercard Premium Charge",
	"MCI": "Mastercard Select Debit",
	"MCM": "Mastercard Corporate Meeting Card",
	"MCO": "Mastercard Corporate",
	"MCP": "Mastercard Corporate Purchasing Card®",
	"MCS": "Mastercard Standard Card",
	"MCT": "Titanium Mastercard®",
	"MCU": "Mastercard Unembossed",
	"MCV": "Merchant-Branded Program",
	"MCW": "World Mastercard® Card",
	"MDB": "Debit Mastercard BusinessCard Card",
	"MDG": "Gold Debit Mastercard®",
	"MDH": "World Debit Embossed",
	"MDI": "Debit Other Unembossed",
	"MDJ": "Debit Mastercard® (Enhanced)",
	"MDL": "Business Debit Other Embossed",
	"MDM": "Middle Market Fleet Card",
	"MDN": "Middle Market Purchasing Card",
	"MDO": "Debit Mastercard Other",
	"MDP": "Platinum Debit Mastercard®",
	"MDQ": "Middle Market Corporate Card",
	"MDR": "Mastercard Debit Brokerage Card",
	"MDS": "Debit Mastercard®",
	"MDT": "Mastercard Business Debit",
	"MDU": "Debit Mastercard Unembossed",
	"MDW": "World Elite Debit Mastercard® (Mastercard Black™ Debit LAC region excluding Mexico)",
	"MEB": "Mastercard Executive BusinessCard Card",
	"MEC": "Mastercard Electronic Commercial",
	"MED": "Debit Mastercard Electronic",
	"MEF": "Mastercard Electronic Payment Account",
	"MEO": "Mastercard Corporate Executive Card®",
	"MEP": "Premium Debit Mastercard",
	"MES": "Mastercard Enterprise Solution",
	"MET": "Titanium Debit Mastercard®",
	"MFB": "Flex World Elite",
	"MFD": "Flex Platinum",
	"MFE": "Flex Charge World Elite",
	"MFH": "Flex World",
	"MFL": "Flex Charge Platinum",
	"MFW": "Flex Charge World",
	"MGF": "Mastercard Government Commercial Card",
	"MGP": "Mastercard Prepaid Gold Payroll",
	"MGS": "Platinum Mastercard® Prepaid General Spend",
	"MHA": "Mastercard Healthcare Prepaid Non-tax",
	"MHB": "Mastercard HSA Substantiated",
	"MHC": "Mastercard Healthcare Credit Nonsubstantiated",
	"MHH": "Mastercard HSA Non-substantiated",
	"MIA": "Mastercard Unembossed Prepaid Student Card",
	"MIB": "Mastercard Credit Electronic Student Card",
	"MIC": "Mastercard Credit Standard Student Card",
	"MID": "Mastercard Debit Unembossed Student Card",
	"MIG": "Mastercard Credit Unembossed Student Card",
	"MIH": "Mastercard Electronic Consumer Non U.S. Student Card",
	"MIJ": "Mastercard Debit Unembossed Non U.S. Student Card",
	"MIK": "Mastercard Electronic Consumer Prepaid Non U.S. Student Card",
	"MIL": "Mastercard Unembossed Prepaid Non U.S. Student Card",
	"MIP": "Mastercard Debit Prepaid Student Card",
	"MIS": "Mastercard Debit Standard Student Card",
	"MIU": "Debit Mastercard Unembossed Outside US",
	"MKA": "Digital Gold Debit",
	"MKB": "Digital Platinum Debit",
	"MKC": "Digital World Debit",
	"MKD": "Digital World Elite Debit",
	"MKE": "Digital Platinum",
	"MKF": "Digital World",
	"MKG": "Digital World Elite",
	"MKH": "Digital World Elite Exclusive",
	"MLA": "Mastercard Central Travel Solutions Air",
	"MLC": "Mastercard Micro-Business Card",
	"MLD": "Mastercard Distribution Card",
	"MLE": "Mastercard Pedágio Prepaid Card (MLE–Mastercard Brazil General Benefits)",
	"MLF": "Mastercard Agro",
	"MLL": "Mastercard Central Travel Solutions Land",
	"MNF": "Mastercard Public Sector Commercial Card",
	"MNW": "World Mastercard Card (Europe)",
	"MOC": "Standard Maestro® Social",
	"MOG": "Maestro® Gold",
	"MOP": "Maestro® Platinum",
	"MOW": "World Maestro",
	"MPA": "Prepaid Mastercard Payroll Card",
	"MPB": "Mastercard Preferred BusinessCard",
	"MPC": "Mastercard Professional Card",
	"MPD": "Mastercard Flex Prepaid",
	"MPE": "Name for GCMS Product ID MPE",
	"MPF": "Prepaid Mastercard Gift Card",
	"MPG": "Prepaid Mastercard Consumer Reloadable Card",
	"MPJ": "Prepaid Debit Mastercard® Card Gold",
	"MPK": "Prepaid Mastercard Government Commercial Card",
	"MPL": "Platinum Mastercard® Card",
	"MPM": "Prepaid Mastercard Consumer Promotion Card",
	"MPN": "Prepaid Mastercard Insurance Card",
	"MPO": "Prepaid Mastercard Other Card",
	"MPR": "Prepaid Mastercard Travel Card",
	"MPT": "Prepaid Mastercard Teen Card",
	"MPV": "Prepaid Mastercard Government Benefit Card",
	"MPW": "Prepaid Mastercard Corporate Card",
	"MPX": "Prepaid Mastercard Flex Benefit Card",
	"MPY": "Prepaid Mastercard Employee Incentive Card",
	"MPZ": "Prepaid Mastercard Emergency Assistance Card",
	"MRB": "Prepaid Mastercard Electronic BusinessCard",
	"MRC": "Prepaid Mastercard Electronic Card",
	"MRD": "Platinum Debit Mastercard® Prepaid General Spend",
	"MRF": "European Regulated Individual Pay",
	"MRG": "Prepaid Mastercard Card Outside US",
	"MRH": "Mastercard Platinum Prepaid Travel Card",
	"MRJ": "Prepaid Mastercard Gold Card",
	"MRK": "Prepaid Mastercard Public Sector Commercial Card",
	"MRL": "Prepaid Mastercard Electronic Commercial",
	"MRO": "Mastercard Rewards Only",
	"MRP": "Standard Retailer Centric Payments",
	"MRS": "Prepaid Mastercard ISIC Student Card",
	"MRW": "Prepaid Mastercard Business Card Credit Outside US",
	"MSA": "Prepaid Maestro Payroll Card",
	"MSB": "Maestro Small Business",
	"MSD": "Deferred Debit Mastercard",
	"MSF": "Prepaid Maestro Gift Card",
	"MSG": "Prepaid Maestro Consumer Reloadable Card",
	"MSI": "Maestro",
	"MSJ": "Prepaid Maestro Gold",
	"MSM": "Prepaid Maestro Consumer Promotion Card",
	"MSN": "Prepaid Maestro Insurance Card",
	"MSO": "Prepaid Maestro Other Card",
	"MSP": "Muse Mastercard",
	"MSR": "Prepaid Maestro Travel Card",
	"MSS": "Maestro Student Card",
	"MST": "Prepaid Maestro Teen Card",
	"MSV": "Prepaid Maestro Government Benefit Card",
	"MSW": "Prepaid Maestro Corporate Card",
	"MSX": "Prepaid Maestro Flex Benefit Card",
	"MSY": "Prepaid Maestro Employee Incentive Card",
	"MSZ": "Prepaid Maestro Emergency Assistance Card",
	"MTP": "Mastercard Platinum Prepaid Travel Card",
	"MUP": "Platinum Debit Mastercard Unembossed",
	"MUS": "Prepaid Mastercard Unembossed US",
	"MUW": "Mastercard World Domestic Affluent",
	"MVA": "Mastercard B2B VIP 1",
	"MVB": "Mastercard B2B VIP 2",
	"MVC": "Mastercard® B2B VIP 3",
	"MVD": "Mastercard B2B VIP 4",
	"MVE": "Mastercard B2B VIP 5",
	"MVF": "Mastercard B2B VIP 6",
	"MVG": "Mastercard B2B VIP 7",
	"MVH": "Mastercard B2B VIP 8",
	"MVI": "Mastercard B2B VIP 9",
	"MVJ": "Mastercard B2B VIP 10",
	"MVK": "Mastercard B2B VIP 11",
	"MVL": "Mastercard B2B VIP 12",
	"MVM": "Mastercard B2B VIP 13",
	"MVN": "Mastercard B2B VIP 14",
	"MWB": "World Mastercard® for Business",
	"MWD": "World Deferred",
	"MWE": "World Elite™",
	"MWF": "Mastercard Humanitarian Prepaid",
	"MWO": "Mastercard Corporate World",
	"MWP": "Mastercard World Prepaid",
	"MWR": "World Retailer Centric Payment",
	"MXG": "Gold Debit Mastercard® Card",
	"NYC": "NYCE Network",
	"OLB": "Maestro Small Business—Delayed Debit",
	"OLG": "Maestro Gold—Delayed Debit",
	"OLI": "ISIC Maestro Student Card—Delayed Debit",
	"OLP": "Maestro Platinum—Delayed Debit",
	"OLS": "Maestro—Delayed Debit",
	"OLW": "World Maestro Delayed Debit",
	"PLU": "PLUS",
	"PRO": "Proprietary Card",
	"PUL": "Pulse",
	"PVA": "Private Label 1",
	"PVB": "Private Label 2",
	"PVC": "Private Label 3",
	"PVD": "Private Label 4",
	"PVE": "Private Label 5",
	"PVF": "Private Label 6",
	"PVG": "Private Label 7",
	"PVH": "Private Label 8",
	"PVI": "Private Label 9",
	"PVJ": "Private Label 10",
	"PVL": "Private label—generic",
	"SAG": "Gold Mastercard® Salary-Immediate Debit",
	"SAL": "Standard Maestro Salary",
	"SAP": "Platinum Mastercard® Salary-Immediate Debit",
	"SAS": "Standard Mastercard Salary-Immediate Debit",
	"SOS": "Standard Mastercard Social-Immediate Debit",
	"STR": "Star Network",
	"SUR": "Prepaid Mastercard Unembossed Outside US",
	"TBE": "Business—Immediate Debit",
	"TCB": "Mastercard Business Card—Immediate Debit",
	"TCC": "Mastercard (Mixed BIN)—Immediate Debit",
	"TCE": "Mastercard Electronic—Immediate Debit",
	"TCF": "Mastercard Fleet Card—Immediate Debit",
	"TCG": "Gold Mastercard Card—Immediate Debit",
	"TCO": "Mastercard Corporate—Immediate Debit",
	"TCP": "Mastercard Purchasing Card—Immediate Debit",
	"TCS": "Mastercard Standard Card—Immediate Debit",
	"TCW": "World Signia Mastercard Card—Immediate Debit",
	"TDN": "Middle Market Mastercard Purchasing Card— Immediate Debit",
	"TEB": "Mastercard Executive BusinessCard Card— Immediate Debit",
	"TEC": "Mastercard Electronic Commercial—Immediate Debit",
	"TEO": "Mastercard Corporate Executive Card— Immediate Debit",
	"TIB": "ISIC Mastercard Electronic Student Card— Immediate Debit",
	"TIC": "ISIC Mastercard Standard Student Card— Immediate Debit",
	"TIU": "Mastercard Unembossed—Immediate Debit",
	"TLA": "Mastercard Central Travel Solutions Air— Immediate Debit",
	"TNF": "Mastercard Public Sector Commercial Card— Immediate Debit",
	"TNW": "Mastercard New World—Immediate Debit",
	"TPB": "Mastercard Preferred Business Card— Immediate Debit",
	"TPC": "Mastercard Professional Card—Immediate Debit",
	"TPL": "Platinum Mastercard—Immediate Debit",
	"TWB": "World Mastercard® Black Edition—ImmediateDebit",
	"VIS": "VisaNet",
	"WBE": "World Mastercard® Black Edition",
	"WDR": "World Debit Mastercard Rewards",
	"WMR": "World Mastercard Rewards",
	"WPD": "World Prepaid Debit",
}
